# CONFIGURACIÓN GENERAL DEL PROYECTO
sonar.projectKey=myd-controles-backend
sonar.projectName=MYD Controles Laravel Backend

# RUTA DE FUENTES (Relativa a esta ubicación, que es la raíz del contenedor /usr/src)
sonar.sources=./app,./database,./routes,./resources
sonar.sourceEncoding=UTF-8

# INCLUSIÓN DE ARCHIVOS ESPECÍFICOS (Incluye .blade.php)
sonar.php.file.suffixes=.php,.phtml,.html,.blade.php 

# EXCLUSIONES (Para acelerar y limpiar el análisis)
sonar.exclusions=./vendor/**,./node_modules/**,./public/**,./storage/**,./tests/**,./bootstrap/**