FROM jenkins/jenkins:lts

USER root

# 1. Instalar utilidades básicas
RUN apt-get update && apt-get install -y \
    lsb-release \
    curl \
    unzip \
    gnupg \
    git \
    ca-certificates

# 2. Instalar Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && apt-get install -y terraform

# 3. Instalar AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# 4. Instalar Docker CLI (Para que Jenkins pueda llamar a otros contenedores)
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

# ¡YA NO INSTALAMOS PYTHON NI CHECKOV AQUÍ!
# Usaremos la imagen oficial de Checkov desde el pipeline.

USER jenkins